language:
- java
rvm:
- 2.3.0
services:
- mysql
jdk:
- oraclejdk7
before_install:
- mysql -u root < initialize.sql
- rvm install 2.3.0
- gem install faraday -v 0.17.3
after_success:
- bash herokuDB.sh
- ls -lah
cache:
  directories:
  - "$HOME/.m2"
addons:
    branches:
    - integrations
    - develop
    - master
dist:
- precise
sudo:
- false
before_deploy:
- bash herokuDB.sh
- ls -lah
deploy:
  provider: heroku
  app: gestor-de-vacaciones
  skip_cleanup: true
  api_key:
    secure: "msnfNvU7/BOmO3SjGlbUeifYbOGTzYfH9mSPrCvGDX6W2e+gzhF4yf7zMYz77Dd+SPooC90GgK9D4CBH7dVPft5llF3PekhVnoi//57ioCTcfFJlqkdvHuZx8OHoNFBJfjfr5P8pGnqYR1Iz0qvksWlgTq/65oXfC27zV2mq5w2AosTVqLG/T0xyiSGNveZb35ic/QgvfEOKzL2Tn2Cygj1ZuEYRGyazzKFUTLSFAdchQn2fNzjjIb8hJ0myM4JO68iGSNQZkFg1P2DUHc9e085/g9KGM1SGRXdMMffMGFdr+0w7z6aLwgtn1OLPuzLyi8OCKwxDL0nskIkqwZGDUZ7vJWSdeivVYfZ6vryBHis3Pl6a6iEKUTfjcO6OC7lchkmtkUXBjCyN9ojxl6/kAz+mXXbLp3EozxN++yR3zRI2W5MQ4TGU0JBefX/E7J83TDKo+ZlQPjn72JNU0eEnz+EMm0rPk7e0KIcA6l4J97GwsBx5y2cD21d7Ben/BeEoJARNK4KZhhPEvjFivO+/g0G3ROhxm7vsH/CKnN+osCIvWDG0I3aPxl2Si6b4ChlVQbDjHJe+tHomtgQ/ee77r8X7rcuLhIEpNxPiaWgd5BKEAZLpZFicHfq9JFfpjnyJxd/3yX29Httaxm7JZTXheAllZe1ogHYjy6Du8hD4Kqs="
