language:
- java
rvm:
- 2.3.0
services:
- mysql
jdk:
- oraclejdk7
before_install:
- mysql -u root < initialize.sql
- rvm install 2.6.0
- gem update --system
- gem --version
- gem install faraday -v 0.17.3
after_success:
- bash herokuDB.sh
- ls -lah
cache:
  directories:
  - "$HOME/.m2"
addons:
    branches:
    - integrations
    - develop
    - master
dist:
- precise
sudo:
- false
before_deploy:
- bash herokuDB.sh
- ls -lah
deploy:
  provider: heroku
  app: gestor-de-vacaciones
  skip_cleanup: true
  api_key:
    secure: 2a8f8c4e-bd05-4a4f-b30c-16b5e1093846
